safe: false
auto: false
server: false
server_port: 4000
pygments: true
future: false
lsi: false
markdown: redcarpet


permalink: /notebook/:year/:month/:title
pagination: 6
url: http://danielgroves.net

maruku:
    use_tex: false
    use_divs: false
    png_engine: blahtex
    png_dir: images/latex
    png_url: /images/latex

redcarpet:
  extensions: []